Diagram ER bazy danych
TortillaZHawaii/partyKLINest pull request #1
Opened 2022-03-10 15:33 UTC by zh-qs

2022-03-14 15:26 UTC, tabiszs commented
Dodałbym średnią opinię do clientów i cleaners jako pola. Po dodaniu oceny wyzwalałby się trigger i obliczał na nowo średnią.

2022-03-14 15:31 UTC, tabiszs commented
2. W Opinii jest możliwość dodania zdjęcia przed i po. Dwa pola na url do storage.
3. Zarówno klient jak i cleaner może być zbanowany
4. Jaki mamy argument, żę mamy tablicę cleaners details.

2022-03-15 17:36 UTC, szymon-zygula requested changes
1. Na pewno nie trzymamy haseł w DB, tym się zajmuje Azure i cały ten ich system
2. U nas średnie lepiej wyliczać za każdym razem jakimś query, będzie najmniej roboty i potencjalnych błędów
3. messLevel raczej lepiej będzie zrobić jako Enum, nie foreign key do innej tabeli

2022-03-16 09:06 UTC, zh-qs commented
> 2. W Opinii jest możliwość dodania zdjęcia przed i po. Dwa pola na url do storage.
> 
>     3. Zarówno klient jak i cleaner może być zbanowany
> 
>     4. Jaki mamy argument, żę mamy tablicę cleaners details.

4. Cleaner, aby móc przyjmować zlecenia, musi wypełnić swoje szczegółowe dane; dałem je w osobnej tabeli, żeby tabela Cleaners nie była tak wielka

2022-03-17 13:27 UTC, szymon-zygula approved these changes

2022-03-18 16:56 UTC, TortillaZHawaii commented
Jest git, nwm jak dobrze w prawdziwej bazie będzie działać relacja 1:1, ewentualnie w kodzie się zrobi giga tablicę.

2022-03-18 16:57 UTC, merged

2022-03-18 20:31 UTC, tabiszs commented
Jest ok